#!/bin/sh

find . -name visited -exec rm {} \;

touch kiddie_gym/pick_up_rugrat
mechanic/pick_up_sport_wagon
hair_salon/pick_up_grandma_with_awesome_beehive
bank/get_more_money
vegetarian_burger_joint/pick_up_sustainable_food
